export const DB = {
  DATA_SOURCE: 'DATA_SOURCE',
  USER: {
    REPOSITORY: 'USER_REPOSITORY',
  },
  POST: {
    REPOSITORY: 'POST_REPOSITORY',
  },
  LIKE: {
    REPOSITORY: 'LIKE_REPOSITORY',
  },
  COMMENT: {
    REPOSITORY: 'COMMENT_REPOSITORY',
  },
  CONVERSATION: {
    REPOSITORY: 'CONVERSATION_REPOSITORY',
  },
  MESSAGE: {
    REPOSITORY: 'MESSAGE_REPOSITORY',
  },
};
