export enum HTTPResponse {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  DELETED = 'DELETED',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_AUTHORIZED = 'NOT_AUTHORIZED',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',

  EMAIL_EXISTS = 'EMAIL_ALREADY_EXISTS',
}
