CREATE TABLE user (
  id VARCHAR(100) NOT NULL PRIMARY KEY,
  cpf CHAR(11) NOT NULL, 
  email VARCHAR(40) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  username VARCHAR(50) NOT NULL,
  bio VARCHAR(250),
  picture VARCHAR(150),
  `password` TEXT NOT NULL,
  `role` VARCHAR(14) NOT NULL DEFAULT 'user',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL
);

CREATE TABLE post (
  id VARCHAR(100) NOT NULL PRIMARY KEY,
  userId VARCHAR(100) NOT NULL,
  `text` TEXT,
  media VARCHAR(150),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (userId) REFERENCES user(id)
);

CREATE TABLE `like` (
  id VARCHAR(100) NOT NULL PRIMARY KEY,
  postId VARCHAR(100) NOT NULL,
  userId VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (postId) REFERENCES post(id),
  FOREIGN KEY (userId) REFERENCES user(id)
);

CREATE TABLE comment (
  id VARCHAR(100) NOT NULL PRIMARY KEY,
  postId VARCHAR(100) NOT NULL,
  userId VARCHAR(100) NOT NULL,
  `text` TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (postId) REFERENCES post(id),
  FOREIGN KEY (userId) REFERENCES user(id)
);

CREATE TABLE `conversation` (
  id VARCHAR(100) NOT NULL PRIMARY KEY,
  fromUserId VARCHAR(100) NOT NULL,
  toUserId VARCHAR(100) NOT NULL,
  accepted BOOLEAN NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (fromUserId) REFERENCES user(id),
  FOREIGN KEY (toUserId) REFERENCES user(id)
);

CREATE TABLE `message` (
  id VARCHAR(100) NOT NULL PRIMARY KEY,
  conversationId VARCHAR(100) NOT NULL,
  fromUserId VARCHAR(100) NOT NULL,
  `text` TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (conversationId) REFERENCES `conversation`(id),
  FOREIGN KEY (fromUserId) REFERENCES user(id)
);