version: '3.7'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: ${MYSQL_HOST}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}

  tsn-phpmyadmin:
    container_name: tsn-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db:${MYSQL_HOST}
    depends_on:
      - db
    ports:
      - '8080:80'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: ${MYSQL_PORT}

  tsn:
    container_name: tsn
    environment:
      - NODE_ENV=dev
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    restart: always
    links:
      - db:${MYSQL_HOST}
    depends_on:
      - db
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ../:/app
      - /app/node_modules/
    expose:
      - '${PORT}'
    command: /bin/sh -c "npm run start:dev"
    env_file: .env

volumes:
  db_data: {}
