version: '3.7'

services:
  tsn_db_prod:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: ${MYSQL_HOST}
    volumes:
      - db_data_prod:/var/lib/mysql
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}

  tsn_phpmyadmin_prod:
    container_name: tsn_phpmyadmin_prod
    image: phpmyadmin/phpmyadmin:5.1.4
    links:
      - tsn_db_prod:${MYSQL_HOST}
    depends_on:
      - tsn_db_prod
    ports:
      - '8080:80'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: ${MYSQL_PORT}

  tsn_prod:
    container_name: tsn_prod
    environment:
      - NODE_ENV=Production
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    restart: always
    links:
      - tsn_db_prod:${MYSQL_HOST}
    depends_on:
      - tsn_db_prod
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ../:/app
      - /app/node_modules/
    expose:
      - '${PORT}'
    command: /bin/sh -c "npm install && npm build && npm run start:prod"
    env_file: .env

volumes:
  db_data_prod: {}
